# ======
# Project Details
# ======
name: 'dbt_snowflake_tpc_sf'
version: '2.0'
config-version: 2
profile: 'snowflake_sample'
require-dbt-version: 1.2.1

# ======
# File Path Configs
# ======
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# ======
# Snowflake Configs
# ======
quoting:
  database: false
  identifier: false
  schema: false
query-comment:
  comment: "{{ query_comment(node) }}"
  append: true

# ======
# Run Hooks
# ======
on-run-start:
    - "{{ resume_warehouse(var('resume_warehouse', false), var('warehouse_name')) }}"
 
on-run-end:
    - "{{ grant_usage_to_schemas() }}"
    - "{{ suspend_warehouse(var('suspend_warehouse', false), var('warehouse_name')) }}"

# ======
# Configs
# ======
seeds:
  +enabled: true
  +schema: intermediate

models:
  core:
    +enabled: true
    +tags: true
    +schema: core

snapshots:
    +target_schema: snapshots

sources:
  tpch_sf10:
    +enabled: true
  
tests:
  +store_failures: true

vars:
  warehouse_name: 
